### PR TITLE
covenant proposal details on alcs to not show errors

### PR DESCRIPTION
**Pull request by urmikgov**

### CODE REVIEW

**Review by trslater — APPROVED** [review]
LGTM 👍

**Comment by dhaselhan** [comment]
I would double check which fields are optional and which aren't. If the field is optional and the user has not entered a value, ALCS should show No Data.

**Comment by urmikgov** [comment]
@dhaselhan i just checked and makes sense to have no data. the bug is about showing errors. made changes

**Review by dhaselhan — APPROVED** [review]
LGTM 👍

**Pull request merged**
