### PR TITLE
Remove erroneous f

### PR DESCRIPTION
**Pull request by dhaselhan**
* Remove f from primary contact section

### CODE REVIEW

**Comment by trslater** [comment]
I only see deletions. Were there meant to be replacement fixed templates?

**Comment by dhaselhan** [comment]
> I only see deletions. Were there meant to be replacement fixed templates?

I'm removing an f from the files that should not be there, thats why each file goes down 5 bytes. I am not deleting the templates.

**Comment by trslater** [comment]
> > I only see deletions. Were there meant to be replacement fixed templates?
> 
> I'm removing an f from the files that should not be there, thats why each file goes down some bytes. I am not deleting the templates.

OK. The GitHub UI is not that clear, but it looks like they're being deleted, but obviously, you would know. Just thought I'd double-check.

**Comment by dhaselhan** [comment]
> OK. The GitHub UI is not that clear, but it looks like they're being deleted, but obviously, you would know. Just thought I'd double-check.

If you look on the left side of files you can see orange marks (edited) instead of red (deleted).
image

**Pull request merged**
